
CREATE TABLE pagespeed 
(

  id 			INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY ,
  timestamp		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  ip			VARCHAR(20) NOT NULL  ,
  user_agent 	VARCHAR(100) NOT NULL ,
  url_id		INTEGER NOT NULL DEFAULT 0  ,
  
  w				INTEGER NOT NULL DEFAULT 0  ,
  o				FLOAT NOT NULL DEFAULT 0  ,
  l				INTEGER NOT NULL DEFAULT 0  ,
  r				INTEGER NOT NULL DEFAULT 0  ,
  t				INTEGER NOT NULL DEFAULT 0  ,
  v				VARCHAR(500) NOT NULL  ,  
   
  pMinifyCSS	FLOAT NOT NULL DEFAULT 0  ,
  pMinifyJS		FLOAT NOT NULL DEFAULT 0  ,
  pOptImgs		FLOAT NOT NULL DEFAULT 0  ,
  pImgDims		FLOAT NOT NULL DEFAULT 0  ,
  pCombineJS	FLOAT NOT NULL DEFAULT 0  ,
  pCombineCSS	FLOAT NOT NULL DEFAULT 0  ,
  pBrowserCache	FLOAT NOT NULL DEFAULT 0  ,
  pProxyCache	FLOAT NOT NULL DEFAULT 0  ,
  pNoCookie		FLOAT NOT NULL DEFAULT 0  ,
  pParallelDl	FLOAT NOT NULL DEFAULT 0  ,
  pCssSelect	FLOAT NOT NULL DEFAULT 0  ,
  pDeferJS		FLOAT NOT NULL DEFAULT 0  ,
  pGzip			FLOAT NOT NULL DEFAULT 0  ,
  pMinRedirect	FLOAT NOT NULL DEFAULT 0  ,
  pCssExpr		FLOAT NOT NULL DEFAULT 0  ,
  pMinDns		FLOAT NOT NULL DEFAULT 0  ,
  pDupeRsrc		FLOAT NOT NULL DEFAULT 0  ,
  pScaleImgs		FLOAT NOT NULL DEFAULT 0  ,
  pMinifyHTML		FLOAT NOT NULL DEFAULT 0  ,
  pMinimizeRequestSize		FLOAT NOT NULL DEFAULT 0  ,
  pOptimizeTheOrderOfStylesAndScripts	FLOAT NOT NULL DEFAULT 0  ,
  pPutCssInTheDocumentHead	FLOAT NOT NULL DEFAULT 0  ,
  pSpecifyCharsetEarly		FLOAT NOT NULL DEFAULT 0
  
  
)