
CREATE TABLE yslow2 
(

  id 			INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY ,
  timestamp		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
  ip			VARCHAR(20) NOT NULL  ,
  user_agent 	VARCHAR(100) NOT NULL ,
  url_id		INTEGER NOT NULL DEFAULT 0  ,
  
  w				INTEGER NOT NULL DEFAULT 0  ,
  o				INTEGER NOT NULL DEFAULT 0  ,
  r				INTEGER NOT NULL DEFAULT 0  ,
  i				VARCHAR(20) NOT NULL  ,
  lt			INTEGER NOT NULL DEFAULT 0  ,
   
  ynumreq		INTEGER NOT NULL DEFAULT 0  ,
  ycdn			INTEGER NOT NULL DEFAULT 0  ,
  yexpires		INTEGER NOT NULL DEFAULT 0  ,
  ycompress		INTEGER NOT NULL DEFAULT 0  ,
  ycsstop		INTEGER NOT NULL DEFAULT 0  ,
  yjsbottom		INTEGER NOT NULL DEFAULT 0  ,
  yexpressions	INTEGER NOT NULL DEFAULT 0  ,
  yexternal		INTEGER NOT NULL DEFAULT 0  ,
  ydns			INTEGER NOT NULL DEFAULT 0  ,
  yminify		INTEGER NOT NULL DEFAULT 0  ,
  yredirects	INTEGER NOT NULL DEFAULT 0  ,
  ydupes		INTEGER NOT NULL DEFAULT 0  ,
  yetags		INTEGER NOT NULL DEFAULT 0  ,
  yxhr			INTEGER NOT NULL DEFAULT 0  ,
  yxhrmethod	INTEGER NOT NULL DEFAULT 0  ,
  ymindom		INTEGER NOT NULL DEFAULT 0  ,
  yno404		INTEGER NOT NULL DEFAULT 0  ,
  ymincookie	INTEGER NOT NULL DEFAULT 0  ,
  ycookiefree	INTEGER NOT NULL DEFAULT 0  ,
  ynofilter		INTEGER NOT NULL DEFAULT 0  ,
  yimgnoscale	INTEGER NOT NULL DEFAULT 0  ,
  yfavicon		INTEGER NOT NULL DEFAULT 0  ,
  details		VARCHAR(500) NOT NULL  
  
)